[feature] Support Autodis and MLP embedding for raw features
alibaba/TorchEasyRec pull request #73
Opened 2024-12-25 09:37 UTC by eric-gecheng

2024-12-25 12:00 UTC, tiankongdeguiji requested changes

2024-12-25 12:00 UTC, tiankongdeguiji commented on tzrec/modules/dense_embedding_collection.py
> +class AutoDisModule(nn.Module):
AutoDisModule -> AutoDisEmbedding

2024-12-25 12:00 UTC, tiankongdeguiji commented on tzrec/modules/dense_embedding_collection.py
> +class MLPModule(nn.Module):
MLPModule -> MLPEmbedding

2024-12-25 12:00 UTC, tiankongdeguiji commented on tzrec/modules/dense_embedding_collection.py
> +                        num_dense_feature=len(
value_dim of dense feature may not equal to 1

2024-12-25 12:00 UTC, tiankongdeguiji commented on tzrec/modules/dense_embedding_collection.py
> +            self.mlp_module_list = nn.ModuleList(
mlp_module_list -> mlp_emb_list

2024-12-25 12:00 UTC, tiankongdeguiji commented on tzrec/modules/dense_embedding_collection.py
> +            mlp_names = [
calc the name and dims in __init__ is better

2024-12-25 12:00 UTC, tiankongdeguiji commented on tzrec/modules/dense_embedding_collection.py
> +                feature_tensor = itemgetter(*(config["feature_names"]))(dense_feature)
use itemgetter and concat to get feature_tensor is not efficient, use regroup is better

2024-12-25 12:00 UTC, tiankongdeguiji commented on tzrec/modules/embedding.py
> +                            if feature.autodis_config:
I think incorporating an `emb_dense_config` as a feature property is better than relying on `autodis_config` and `mlp_config`. This approach allows us to introduce additional dense embedding types without the need to modify `embedding.py`. Instead, we simply add the new type to the `dense_embedding_collection`.

2024-12-26 01:06 UTC, eric-gecheng commented on tzrec/modules/dense_embedding_collection.py
> +            self.mlp_module_list = nn.ModuleList(
renamed to mlp_emb_module_list since there's another variable named mlp_emb_list already.

2024-12-26 01:06 UTC, eric-gecheng commented on tzrec/modules/dense_embedding_collection.py
> +class MLPModule(nn.Module):
change done

2024-12-26 01:06 UTC, eric-gecheng commented on tzrec/modules/dense_embedding_collection.py
> +class AutoDisModule(nn.Module):
change done.

2024-12-26 02:46 UTC, eric-gecheng commented on tzrec/modules/dense_embedding_collection.py
> +                feature_tensor = itemgetter(*(config["feature_names"]))(dense_feature)
fixed

2024-12-26 02:46 UTC, eric-gecheng commented on tzrec/modules/dense_embedding_collection.py
> +            mlp_names = [
fixed

2024-12-26 04:14 UTC, eric-gecheng commented on tzrec/modules/dense_embedding_collection.py
> +                        num_dense_feature=len(
value_dim check added in feature.py

2024-12-26 04:14 UTC, eric-gecheng commented on tzrec/modules/embedding.py
> +                            if feature.autodis_config:
fixed, logic is simplified in embedding.py

2024-12-27 01:34 UTC, tiankongdeguiji approved these changes
LGTM

2024-12-27 01:34 UTC, merged